## 避免和 server 工程端口冲突
server:
  port: 8083


spring:
  dubbo:
    application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
      name: Consumer
    registry:                 #注册中心配置，用于配置连接注册中心相关信息。
      address: zookeeper://192.168.40.155:2181
    protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
      name: dubbo
      port: 20880
    scan: org.spring.springboot.service  #服务暴露与发现消费所在的package