server:
  port: 8081
mybatis:
  configLocation: classpath:mybatis/mybatis-config.xml

  # 加载全局的配置文件
   # configuration: classpath:mybatis/mybatis-config.xml
   # 配置类型别名
  # typeAliasesPackage: com.maochong.mybatis
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  # mapperLocations: classpath:mybatis/mapper/*.xml
